### ISSUE TITLE
Unit test error with python 3

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/libSBOL#193]
Building libSBOL on Ubuntu 16.04 with `SBOL_BUILD_PYTHON2=ON`, all unit tests succeed. Building with `SBOL_BUILD_PYTHON3=ON`, I get the following unit test error:

```
======================================================================
ERROR: testPrimarySequenceIteration (__main__.TestComponentDefinitions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_tests.py", line 503, in testPrimarySequenceIteration
    gene.assemblePrimaryStructure([ promoter, RBS, CDS, terminator ])
  File "/users/foo/install_x64/wrapper/sbol/libsbol.py", line 4928, in assemblePrimaryStructure
    return _libsbol.ComponentDefinition_assemblePrimaryStructure(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'ComponentDefinition_assemblePrimaryStructure'.
  Possible C/C++ prototypes are:
    sbol::ComponentDefinition::assemblePrimaryStructure(std::vector< std::string,std::allocator< std::string > >)
    sbol::ComponentDefinition::assemblePrimaryStructure(std::vector< sbol::ComponentDefinition *,std::allocator< sbol::ComponentDefinition * > >)
    sbol::ComponentDefinition::assemblePrimaryStructure(std::vector< sbol::ComponentDefinition *,std::allocator< sbol::ComponentDefinition * > >,sbol::Document &)
    sbol::ComponentDefinition::assemblePrimaryStructure(PyObject *,PyObject *)
    sbol::ComponentDefinition::assemblePrimaryStructure(PyObject *)
```

Here are the steps I took to build libSBOL with python 3:

```
git clone https://github.com/SynBioDex/libSBOL.git
cd libSBOL
git checkout v2.3.0.0
git submodule update --init --recursive
cmake -DCMAKE_INSTALL_PREFIX=~/install_x64 -DSBOL_BUILD_SHARED=ON \
    -DSBOL_BUILD_PYTHON3=ON
make
make install
```

To run the unit tests:

```
cd ~/install_x64/wrapper/sbol/
python3 unit_tests.py
```

**Comment by bbartley** [comment]
Thanks for logging this issue @tcmitchell. Commit 022cf50 fixes this issue.

It was not obvious why this error occurs in Python 3 and not Python 2 bindings, but it is related to how SWIG manages overloaded function signatures. The fix involves using the SWIG %ignore directive to selectively ignore some signatures (which didn't need to be exposed to a Python user anyway).
