### ISSUE TITLE
SSL issue with pip pysbol package on Linux

### ISSUE THREAD

**Issue by tim-tx** [SynBioDex/libSBOL#202]
Python 2 and 3 affected (2.7 and 3.6 tested).

Steps to reproduce:

    $ pip install pysbol --user
    $ python
    >>> from sbol import *
    >>> partshop = PartShop('https://synbiohub.org/public/igem')
    >>> records = partshop.search('interlab')

Result:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/me/.local/lib/python3.6/site-packages/sbol/libsbol.py", line 8643, in search
        val = _libsbol.PartShop_search(self, *args)
    RuntimeError: Attempt to validate online failed with Problem with the SSL CA cert (path? access rights?)

The above steps work against pysbol built manually from the libSBOL source.

**Comment by bbartley** [comment]
Hi Tim,

I've attempted to correct this issue by recompiling libpython with OpenSSL and deploying a new wheel.

At your convenience, please update to the new wheel and re-test with Python3.6.

 ```
$ pip install --user --upgrade
```

This should upgrade your package to  pySBOL-2.3.0.post20-cp36-cp36m-manylinux1_x86_64.whl

**Comment by tim-tx** [comment]
Here is the result:

    Python 3.6.6 (default, Jun 27 2018, 13:11:40) 
    [GCC 8.1.1 20180531] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sbol
    Traceback (most recent call last):
      File "/home/tsj/.local/lib/python3.6/site-packages/sbol/libsbol.py", line 19, in swig_import_helper
	return importlib.import_module(mname)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
	return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 571, in module_from_spec
      File "<frozen importlib._bootstrap_external>", line 922, in create_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    ImportError: /home/tsj/.local/lib/python3.6/site-packages/sbol/_libsbol.so: undefined symbol: MD5_Init

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/tsj/.local/lib/python3.6/site-packages/sbol/__init__.py", line 6, in <module>
	from sbol.sbol import *
      File "/home/tsj/.local/lib/python3.6/site-packages/sbol/sbol.py", line 17, in <module>
	from .libsbol import *
      File "/home/tsj/.local/lib/python3.6/site-packages/sbol/libsbol.py", line 22, in <module>
	_libsbol = swig_import_helper()
      File "/home/tsj/.local/lib/python3.6/site-packages/sbol/libsbol.py", line 21, in swig_import_helper
	return importlib.import_module('_libsbol')
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
	return _bootstrap._gcd_import(name[level:], package, level)
    ModuleNotFoundError: No module named '_libsbol'

**Comment by bbartley** [comment]
@tim-tx Hi Tim, I've made another attempt at building the Linux wheel with support for secure HTTP:

At your convenience, please update to the new wheel and test with Python3.6.

$ pip install --user --upgrade

This should upgrade your package to pySBOL-2.3.0.post21-cp36-cp36m-manylinux1_x86_64.whl

**Comment by tim-tx** [comment]
@bbartley Hi Bryan, I did the upgrade, though I seem to be running into the same issue:

    $ python3.6 -m pip show pysbol
    Name: pySBOL
    Version: 2.3.0.post21
    ...

And then:

    $ python3.6                 
    Python 3.6.6 (default, Aug 26 2018, 01:20:38) 
    [GCC 8.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from sbol import *
    Traceback (most recent call last):
      File "/home/lab/.local/lib/python3.6/site-packages/sbol/libsbol.py", line 19, in swig_import_helper
	return importlib.import_module(mname)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
	return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 571, in module_from_spec
      File "<frozen importlib._bootstrap_external>", line 922, in create_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    ImportError: /home/lab/.local/lib/python3.6/site-packages/sbol/_libsbol.so: undefined symbol: MD5_Init

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/lab/.local/lib/python3.6/site-packages/sbol/__init__.py", line 6, in <module>
	from sbol.sbol import *
      File "/home/lab/.local/lib/python3.6/site-packages/sbol/sbol.py", line 17, in <module>
	from .libsbol import *
      File "/home/lab/.local/lib/python3.6/site-packages/sbol/libsbol.py", line 22, in <module>
	_libsbol = swig_import_helper()
      File "/home/lab/.local/lib/python3.6/site-packages/sbol/libsbol.py", line 21, in swig_import_helper
	return importlib.import_module('_libsbol')
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
	return _bootstrap._gcd_import(name[level:], package, level)
    ModuleNotFoundError: No module named '_libsbol'

**Comment by tim-tx** [comment]
On the wheel:

    $ ldd /home/lab/.local/lib/python3.6/site-packages/sbol/_libsbol.so    
	    linux-vdso.so.1 (0x00007ffd2db2b000)
	    libpython3.6m.so.1.0 => /usr/lib/libpython3.6m.so.1.0 (0x00007f54a1f66000)
	    libxslt-6cbe83bf.so.1.1.17 => /home/lab/.local/lib/python3.6/site-packages/sbol/.libs/libxslt-6cbe83bf.so.1.1.17 (0x00007f54a1d28000)
	    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f54a1b99000)
	    libm.so.6 => /usr/lib/libm.so.6 (0x00007f54a1a14000)
	    libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f54a19fa000)
	    libc.so.6 => /usr/lib/libc.so.6 (0x00007f54a1836000)
	    libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f54a1813000)
	    libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f54a180e000)
	    libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f54a1809000)
	    libxml2-8ed442f7.so.2.6.26 => /home/lab/.local/lib/python3.6/site-packages/sbol/.libs/libxml2-8ed442f7.so.2.6.26 (0x00007f54a14b6000)
	    libz-a147dcb0.so.1.2.3 => /home/lab/.local/lib/python3.6/site-packages/sbol/.libs/libz-a147dcb0.so.1.2.3 (0x00007f54a12a1000)

And on the version I built from libSBOL (where I don't see the `MD5_Init` issue as above):

    $ ldd /usr/lib/python3.6/site-packages/sbol/_libsbol.so
    ldd: warning: you do not have execution permission for `/usr/lib/python3.6/site-packages/sbol/_libsbol.so'
	    linux-vdso.so.1 (0x00007ffe829f1000)
	    libpython3.6m.so.1.0 => /usr/lib/libpython3.6m.so.1.0 (0x00007f486d6a8000)
	    libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f486d428000)
	    libxslt.so.1 => /usr/lib/libxslt.so.1 (0x00007f486d1e9000)
	    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f486d05a000)
	    libm.so.6 => /usr/lib/libm.so.6 (0x00007f486ced5000)
	    libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f486cebb000)
	    libc.so.6 => /usr/lib/libc.so.6 (0x00007f486ccf5000)
	    libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f486ccd4000)
	    libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f486cccf000)
	    libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f486ccca000)
	    libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x00007f486caa5000)
	    libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007f486c888000)
	    libpsl.so.5 => /usr/lib/libpsl.so.5 (0x00007f486c676000)
	    libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f486c60a000)
	    libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f486c386000)
	    libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007f486c138000)
	    libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007f486be4f000)
	    libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007f486bc1c000)
	    libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007f486ba16000)
	    libz.so.1 => /usr/lib/libz.so.1 (0x00007f486b7ff000)
	    libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007f486b697000)
	    /usr/lib64/ld-linux-x86-64.so.2 (0x00007f486e650000)
	    libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007f486b317000)
	    libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007f486b10a000)
	    libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007f486af04000)
	    libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f486aeeb000)
	    libicuuc.so.62 => /usr/lib/libicuuc.so.62 (0x00007f486ad24000)
	    liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f486aafe000)
	    libicudata.so.62 => /usr/lib/libicudata.so.62 (0x00007f4869163000)

It seems `MD5_Init` comes from `libcrypto` or `libssl`, perhaps there's an LDFLAGS issue. Don't know if this is helpful: https://flameeyes.blog/2008/11/20/misguided-link-and-as-needed/

**Comment by bbartley** [comment]
Hi, the latest version of pySBOL now has a workaround for this issue.  Before sending a request to synbiohub, you can configure the certificate path for your Linux distribution, as follows:

`Config.setOption('ca-path', path_to_ca_file)`

Where `path_to_ca_file` is defined as follows for different Linux distros:
Debian/Ubuntu:  "/etc/ssl/certs/ca-certificates.crt"
Fedora/RHEL:  "/etc/pki/tls/certs/ca-bundle.crt" 
OpenSUSE : "/var/lib/ca-certificates/ca-bundle.pem"

By default the certificate path is configured for Red Hat Linux

**Comment by tim-tx** [comment]
Can you deploy a Linux / Python 3.7 wheel for pySBOL-2.3.2? If I can get a wheel for this I'm happy to test. I wonder if there isn't some appropriate abstraction layer that can tell you where to look, that could be used instead of this workaround in the future? As I remember I did not have any SSL issues when I built the Python bindings from libSBOL directly.

**Comment by bbartley** [comment]
@tim-tx There is now a Python 3.7 wheel available for Linux that should auto-configure the certificate path.  It seems to work on Ubuntu and CentOS so far:

 ```pip3 install pysbol --upgrade --user```

You should get:
```Successfully installed pysbol-2.3.3.post6```
